spring.application.name=DOCHUB
server.port=8080
server.address=0.0.0.0

# H2 Database Setup
spring.datasource.url=jdbc:h2:file:./data/collabdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Thymeleaf
spring.thymeleaf.check-template-location=false
